### ISSUE TITLE
Add key authentication on mongodb

### ISSUE THREAD

**Issue by InfraArtists** [SanazSadr/DevOps#1]
MongoDB replica set needs both user account and keyfile. Keyfile seems for authentication between servers in the replica set

Create key on master node:

```
cd
openssl rand -base64 741 > /opt/mongo/keys/mongodb.key
chmod 400 mongodb.key
```
Copy key to the same place on slaves node

```
scp /opt/manog/keys/mongodb.key  USER@SERVERIP: /opt/mongo/keys/mongodb.key
```

edit `mongodb.conf` file and add:

```
replication:
  replSetName: rs0

security:
  authorization: enabled
  keyFile:  /opt/mongo/keys/mongodb.key
```

Restart the service and check replication
